name: flutter_ovumb_app_version1
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.2.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  path: ^1.8.2
  edge_detection:
    path: ../
  dropdown_button2: ^2.3.9
  table_calendar: ^3.0.8
  flutter_localizations:
    sdk: flutter
  percent_indicator: ^4.2.2
  syncfusion_flutter_charts: ^20.4.51
  showcaseview: ^2.0.1
  shared_preferences: ^2.0.18
  lottie: ^2.3.0
  flutter_local_notifications: ^8.2.0
  timezone: ^0.8.0
  url_launcher: ^6.1.10
  device_preview: ^1.1.0
  fluttertoast: ^8.2.1
  flutter_phone_direct_caller: ^2.1.1
  video_player: ^2.6.1
  vector_math: ^2.1.4
  equatable: ^2.0.5
  dio: ^5.1.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  intl: ^0.19.0
  flutter_offline: ^2.1.0
  scrollable_positioned_list: ^0.3.8
  horizontal_picker: ^1.2.0
  qr_code_scanner: ^1.0.1
  audioplayers: ^4.0.1
  app_settings: ^5.0.0
  flutter_xlider: ^3.5.0
  shimmer: ^3.0.0
  flutter_inappwebview: ^5.8.0
  cached_network_image: ^3.3.0
  timelines: ^0.1.0
  flutter_rating_bar: ^4.0.1
  image: ^3.3.0
  animated_text_kit: ^4.2.2
  rxdart: ^0.27.7
  flutter_launcher_icons: ^0.11.0
  pinput: ^3.0.1
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^2.3.9
  youtube_player_flutter: ^8.1.2
  flutter_screenutil: ^5.9.1
  firebase_messaging: ^14.7.19
  firebase_core: ^2.17.0
  googleapis_auth: ^1.4.1
  carousel_slider: ^4.2.1
  syncfusion_flutter_pdfviewer: ^20.4.54
  webview_flutter: ^4.8.0
  image_picker: ^1.1.2
  photo_gallery: ^2.2.1
  http_parser: ^4.0.2
  mime: ^1.0.5
  device_info_plus: ^9.1.2
  dotted_border: ^2.1.0

flutter_icons:
  android: "ic_logo"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/buttons/
    - assets/logo/
    - assets/images/
    - assets/icons/
    - assets/stores/
    - assets/sounds/
    - assets/animations/
    - assets/

  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 100
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 300
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
